-- DROP TABLE NullTb1
CREATE TABLE NullTbl
(col_1 VARCHAR(32) );

START TRANSACTION;
INSERT INTO NullTbl VALUES (NULL);
INSERT INTO NullTbl VALUES (NULL);
INSERT INTO NullTbl VALUES (NULL);
COMMIT;
-- 

SELECT * FROM NullTbl;

SELECT COUNT(*), COUNT(col_1)
FROM NullTbl;

